### ISSUE TITLE
Composition pages and search

### ISSUE THREAD

**Issue by MortenHofft** [gbif/content-ws#13]
Currently search for pages of type composition isn't very effective. We only search the summary and title of the core entry. All the associated blocks are ignored.

Example entry 
https://www.gbif.org/composition/1chRptI6NOaMtIQro0F8FI/exploring-edna-data

can be found by [text from the summary](https://www.gbif.org/resource/search?q=included%20expert%20speakers%20sharing%20their%20insights%20and%20experiences%20with%20eDNA)

But not from the [blocks that make up the page](https://www.gbif.org/resource/search?q=learned%20about%20the%20current%20practice%20for%20publishing%20eDNA%20data%20and%20participated%20in%20discussions)

Would it make sense to include title+summary+body of all immedate children blocks into a free text search field (not exposed in the response)?
Would it be useful @dnoesgaard and possible @fmendezh?

The same goes for programmes pages and their block field

**Comment by dnoesgaard** [comment]
This is definitely useful and important as we're using the composition model more and more.

**Comment by MortenHofft** [comment]
Should all blocks be included @dnoesgaard or only a subset of them?  
I'm thinking specifically of a list of news for example. Those might be a bit odd to include as searchable text for the page that simply links to them? On the other hand the "main" entry will probably be a better match that is boosted more anyhow.

And does the fields I suggested make sense to you: title+summary+body ?

And how about the depth. Is it only immedate children of how many levels deep make sense? It depends on how you generally compose the pages I guess. We could also have a flag for each block that tells if it should be included or not?

**Comment by dnoesgaard** [comment]
I'd like @javiesgm and @kcopas to weigh in here...

**Comment by kcopas** [comment]
> On the other hand the "main" entry will probably be a better match that is boosted more anyhow.

What do you mean by "main entry", @MortenHofft ? And how does it relate to the news items?

I'm kind of inclined to think that the title+summary+body for the latter would actually be quite useful in improving the search result.

**Comment by javiesgm** [comment]
The Header block is a must, and the Title + summary + body makes sense to me. On a related matter, could we flag these header blocks as the "Real" titles of these composition pages? The main composition title serves an internal purpose sometimes. I was thinking of SEO mostly. 

Here is how Google indexed this composition sometime ago:
![Screenshot 2023-05-23 at 09 53 20](https://github.com/gbif/content-ws/assets/14220404/656a483b-f2f3-4d36-873f-2f51992d4a9d)

**Comment by fmendezh** [comment]
@MortenHofft currently we have an _all field in which we copy all keywords and text fields, are you proposing a new field for title, summary and body only?

**Comment by MortenHofft** [comment]
This is is unrelated to SEO. If we have issues with that, then please create another issue. It is also unrelated to page rendering. It is about the quality of the search results on GBIF.org. Which is driven by our own ElasticSearch instance.

We can also just do something and then discuss afterwards if you prefer. If you have an interest in knowing what is included, and what I suggest then read on.

For all content types we can search for fields that are on the main entry. But rarely - if ever - on referenced items.

For a news item that reference a primary image, that isn't really an issue. But for Compositions (and now programmes) that approach isn't ideal for search. The composition item has a title, a summary and then a list references to blocks that the page is build with. Only the title and summary is included in elastic search. So any text written in one of the blocks is not in the index. 

**Example**
For the [Ambassador](https://www.gbif.org/composition/6iHKXo8pUyRPJ2Ut0683Z8/ambassadors) composition, we can find it in search by typing the [first sentence in the summary](https://www.gbif.org/resource/search?q=A%20corps%20of%20professionals%20advocating%20best%20practices%20in%20open%20sharing%20and%20transparent%20use%20of%20biodiversity%20data.) (which isn't shown on the website). But not by typing the [first sentence in the first block ](https://www.gbif.org/resource/search?q=The%20success%20of%20GBIF%20depends%20in%20part%20on%20establishing%20a%20good%20understanding%20within%20research%20and%20policy%20communities). Because text in references items are not included in the search index.

We can fix that. We just need to add include text from referenced items into the `_all` field that @fmendezh mentions.

But how much to include is the question. So taking the GBIF and Soil entry as an example:

* [GBIF and Soil](https://app.contentful.com/spaces/uo17ejk9rkwj/entries/uckZeBqu6WqD1F3AZNj1h) has title+summary and blocks
* Blocks:
  * Header
  * Text
  * [Features](https://app.contentful.com/spaces/uo17ejk9rkwj/entries/1pV8hud2TeQHYCG8Jw1lCM?previousEntries=uckZeBqu6WqD1F3AZNj1h) has title+body + list of cards
    * [News item](https://app.contentful.com/spaces/uo17ejk9rkwj/entries/232EKewXfNDeh0U7vAUbsG?previousEntries=uckZeBqu6WqD1F3AZNj1h,1pV8hud2TeQHYCG8Jw1lCM) which has title+summary+body+referenced topics etc.
    * Feature
    * Feature

So how much of that do we include in the searchable `all` text field for the "GBIF and Soil"-entry is the question.

We can choose to iterate over all blocks and add the text from those. And from anything they reference. And anything they reference. Doing so would mean that the entire news item would be indexed again for the "GBIF and Soil"-page.

Or we could choose to have a maximum depth. And a filter on what types we include.

One approach that I think sounds reasonable is that we include title+summary+body fields. And iterate over any referenced items in the blocks field. And that we only consider the immediate children. So for the GBIF Soil example we would only include
the main entry and the immediate children:
* the header block (GBIF and soil)
* Feature text block (intro to soil)
* And for the 4 feature text blocks, we include the title +body, but not list of news/features they reference

That means that you cannot search for text on one of the feature cards. But you can search for text in the header and text blocks.
The filter is that only these contentypes will be indexed: https://app.contentful.com/spaces/uo17ejk9rkwj/content_types?order.fieldId=name&order.direction=ascending&searchTerm=block
And only their title, summary, body fields.

**Comment by dnoesgaard** [comment]
I agree with @MortenHofft's suggestion!

**Comment by javiesgm** [comment]
+1

**Comment by MortenHofft** [comment]
This looks done to me, at least the examples in the issue now works. I will close it.
